# Generated by Django 5.0.7 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenCafe',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('origen', models.CharField(db_column='Origen', max_length=80)),
            ],
            options={
                'db_table': 'tblOrigenCafe',
            },
        ),
    ]
