# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_tareas', '0001_initial'),
        ('inventario_cafe', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionTueste',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('cat_limpieza', models.BooleanField(blank=True, db_column='CatLimpieza', null=True)),
                ('cat_quaker', models.BooleanField(blank=True, db_column='CatQuaker', null=True)),
                ('peso_quaker', models.FloatField(blank=True, db_column='PesoQuaker', null=True)),
                ('cat_grupo1', models.BooleanField(blank=True, db_column='CatGrupo1', null=True)),
                ('desc_grupo1', models.CharField(blank=True, db_column='DescGrupo1', max_length=20, null=True)),
                ('peso_grupo1', models.FloatField(blank=True, db_column='PesoGrupo1', null=True)),
                ('cat_grupo2', models.BooleanField(blank=True, db_column='CatGrupo2', null=True)),
                ('desc_grupo2', models.CharField(blank=True, db_column='DescGrupo2', max_length=20, null=True)),
                ('peso_grupo2', models.FloatField(blank=True, db_column='PesoGrupo2', null=True)),
                ('cat_grupo3', models.BooleanField(blank=True, db_column='CatGrupo3', null=True)),
                ('desc_grupo3', models.CharField(blank=True, db_column='DescGrupo3', max_length=20, null=True)),
                ('peso_grupo3', models.FloatField(blank=True, db_column='PesoGrupo3', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('estado_tareas', models.ForeignKey(blank=True, db_column='IdEstadoTareas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_tareas.estadotarea')),
                ('inventario_cafe', models.ForeignKey(blank=True, db_column='IdInventarioCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_cafe.inventariocafe')),
                ('orden', models.ForeignKey(blank=True, db_column='IdOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.orden')),
            ],
            options={
                'db_table': 'tblSeleccionTueste',
            },
        ),
    ]
