# Generated by Django 5.0.14 on 2026-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccion_tueste', '0002_remove_inventario_cafe_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecciontueste',
            name='notas',
            field=models.CharField(blank=True, db_column='Notas', max_length=500, null=True),
        ),
    ]
