# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_inven_cafe', '0001_initial'),
        ('estado_tareas', '0001_initial'),
        ('nivel_tueste', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tueste',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('batche', models.IntegerField(blank=True, db_column='Batche', null=True)),
                ('peso_cafe_vede', models.FloatField(blank=True, db_column='PesoCafeVede', null=True)),
                ('peso_cafe_tostado', models.FloatField(blank=True, db_column='PesoCafeTostado', null=True)),
                ('rendimiento', models.FloatField(blank=True, db_column='Rendimiento', null=True)),
                ('peso_cafe_vede_total', models.FloatField(blank=True, db_column='PesoCafeVedeTotal', null=True)),
                ('peso_cafe_tostado_total', models.FloatField(blank=True, db_column='PesoCafeTostadoTotal', null=True)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=40, null=True)),
                ('notas_op', models.CharField(blank=True, db_column='NotasOp', max_length=40, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, db_column='FechaHoraInicio', null=True)),
                ('consumo_gas', models.FloatField(blank=True, db_column='ConsumoGas', null=True)),
                ('consumo_kwh', models.FloatField(blank=True, db_column='ConsumoKWH', null=True)),
                ('temp_deshidratacion', models.FloatField(blank=True, db_column='TempDeshidratacion', null=True)),
                ('tiempo_deshidratacion', models.TimeField(blank=True, db_column='TiempoDeshidratacion', null=True)),
                ('temp1_crack', models.FloatField(blank=True, db_column='Temp1Crack', null=True)),
                ('tiempo1_crack', models.TimeField(blank=True, db_column='Tiempo1Crack', null=True)),
                ('temp_fin_curva', models.FloatField(blank=True, db_column='TempFinCurva', null=True)),
                ('tiempo_fin_curva', models.TimeField(blank=True, db_column='TiempoFinCurva', null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, db_column='FechaHoraFin', null=True)),
                ('tempo_tueste', models.TimeField(blank=True, db_column='TempoTueste', null=True)),
                ('tiempo_enfriamiento', models.TimeField(blank=True, db_column='TiempoEnfriamiento', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('estado_tareas', models.ForeignKey(blank=True, db_column='IdEstadoTareas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_tareas.estadotarea')),
                ('inventario_cafe_estado', models.ForeignKey(blank=True, db_column='IdInventarioCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_inven_cafe.estadoinvencafe')),
                ('nivel_tueste', models.ForeignKey(blank=True, db_column='IdNivelTueste', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nivel_tueste.niveltueste')),
                ('orden', models.ForeignKey(blank=True, db_column='IdOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.orden')),
            ],
            options={
                'db_table': 'tblTueste',
            },
        ),
    ]
