# Generated by Django 5.0.7 on 2025-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_inven_cafe', '0001_initial'),
        ('estado_tareas', '0001_initial'),
        ('nivel_tueste', '0001_initial'),
        ('ordenes', '0002_orden_idx_orden_fecha_orden_idx_orden_cliente_and_more'),
        ('tueste', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tueste',
            index=models.Index(fields=['fecha_ingreso'], name='idx_tueste_fecha'),
        ),
    ]
