# Generated by Django 5.0.14 on 2025-09-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_cafe', '0001_initial'),
        ('tueste', '0002_tueste_idx_tueste_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tueste',
            name='inventario_cafe_estado',
            field=models.ForeignKey(blank=True, db_column='IdInventarioCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_cafe.estadocafe'),
        ),
    ]
