# Generated by Django 5.0.14 on 2025-09-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tueste', '0004_fix_fk_tueste_estado_cafe'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=r"""
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID(N'dbo.tblTueste') AND name = N'FK_tblTueste_tblInventarioCafe')
    ALTER TABLE [dbo].[tblTueste] DROP CONSTRAINT [FK_tblTueste_tblInventarioCafe];

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID(N'dbo.tblTueste') AND name = N'FK_tblTueste_tblEstadoCafe')
    ALTER TABLE [dbo].[tblTueste] DROP CONSTRAINT [FK_tblTueste_tblEstadoCafe];

IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'IdInventarioCafe' AND Object_ID = Object_ID(N'dbo.tblTueste'))
    ALTER TABLE [dbo].[tblTueste] DROP COLUMN [IdInventarioCafe];
                    """,
                    reverse_sql=r"""
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'IdInventarioCafe' AND Object_ID = Object_ID(N'dbo.tblTueste'))
    ALTER TABLE [dbo].[tblTueste] ADD [IdInventarioCafe] INT NULL;
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='tueste',
                    name='inventario_cafe_estado',
                ),
            ],
        )
    ]
