# Generated by Django 5.0.7 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaTueste',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('temp_set_point', models.IntegerField(blank=True, db_column='TempSetPont', null=True)),
                ('temp_tost', models.IntegerField(blank=True, db_column='TempTost', null=True)),
                ('porcentaje_aire', models.IntegerField(blank=True, db_column='PorcentajeAire', null=True)),
                ('porcentaje_gas', models.IntegerField(blank=True, db_column='PorcentajeGas', null=True)),
            ],
            options={
                'db_table': 'tblCurvasTueste',
            },
        ),
    ]
