# Generated by Django 5.0.7 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvento',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_utc', models.DateTimeField(db_column='FechaUtc')),
                ('tabla', models.CharField(db_column='Tabla', max_length=128)),
                ('accion', models.CharField(db_column='Accion', max_length=1)),
                ('clave', models.CharField(db_column='Clave', max_length=200)),
                ('actor_user_id', models.IntegerField(blank=True, db_column='ActorUserId', null=True)),
                ('actor_username', models.CharField(blank=True, db_column='ActorUsername', max_length=150, null=True)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=50, null=True)),
                ('correlation_id', models.UUIDField(blank=True, db_column='CorrelationId', null=True)),
                ('datos', models.TextField(blank=True, db_column='Datos', null=True)),
                ('app_name', models.CharField(blank=True, db_column='AppName', max_length=128, null=True)),
                ('host', models.CharField(blank=True, db_column='Host', max_length=128, null=True)),
                ('usuario_sql', models.CharField(blank=True, db_column='UsuarioSQL', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Log de Evento',
                'verbose_name_plural': 'Log de Eventos',
                'db_table': 'tblLogEventos',
            },
        ),
    ]
