# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_empaque', '0001_initial'),
        ('estado_inven_cafe', '0001_initial'),
        ('estado_tareas', '0001_initial'),
        ('ordenes', '0001_initial'),
        ('tamano_empaque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('cant_empaque', models.IntegerField(blank=True, db_column='CantEmpaque', null=True)),
                ('cant_empacada', models.IntegerField(blank=True, db_column='CantEmpacada', null=True)),
                ('cant_etiquetas', models.IntegerField(blank=True, db_column='CantEtiquetas', null=True)),
                ('emp_clientes', models.IntegerField(blank=True, db_column='EmpClientes', null=True)),
                ('total_empaques', models.IntegerField(blank=True, db_column='TotalEmpaques', null=True)),
                ('total_etiquetas', models.IntegerField(blank=True, db_column='TotalEtiquetas', null=True)),
                ('total_paquetes', models.IntegerField(blank=True, db_column='TotalPaquetes', null=True)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=40, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('estado_inven_cafe', models.ForeignKey(blank=True, db_column='IdInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_inven_cafe.estadoinvencafe')),
                ('estado_tareas', models.ForeignKey(blank=True, db_column='IdEstadoTareas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_tareas.estadotarea')),
                ('orden', models.ForeignKey(blank=True, db_column='IdOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.orden')),
                ('orden_empaque', models.ForeignKey(blank=True, db_column='IdOrdenEmpaque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_empaque.cafeempaque')),
                ('tamano', models.ForeignKey(blank=True, db_column='IdTamano', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamano_empaque.tamanoempaque')),
            ],
            options={
                'db_table': 'tblEmpaques',
            },
        ),
    ]
