# Generated by Django 5.0.7 on 2025-09-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0003_fix_fk_empaques_estado_cafe'),
        ('tamano_empaque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaque',
            name='tamano',
            field=models.ForeignKey(blank=True, db_column='IdTamanoEmpaque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamano_empaque.tamanoempaque'),
        ),
    ]
