# Generated by Django 5.0.7 on 2025-09-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0004_alter_empaque_tamano'),
        ('molienda', '0004_fix_fk_molienda_estado_cafe'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # No toques la BD (columna ya existe); solo actualiza el estado del modelo
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='empaque',
                    name='molienda',
                    field=models.ForeignKey(blank=True, db_column='IdMolienda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='molienda.molienda'),
                ),
            ],
        ),
    ]
