# Generated by Django 5.0.7 on 2025-09-14 20:26

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0005_empaque_molienda'),
        ('tamano_empaque', '0001_initial'),
    ]

    def forwards_raw(apps, schema_editor):
        with connection.cursor() as cursor:
            cursor.execute("""
            IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'IdTamano' AND Object_ID = Object_ID(N'dbo.tblEmpaques'))
            BEGIN
                EXEC sp_rename 'dbo.tblEmpaques.IdTamano', 'IdTamanoEmpaque', 'COLUMN';
            END
            """)

    def backwards_raw(apps, schema_editor):
        with connection.cursor() as cursor:
            cursor.execute("""
            IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'IdTamanoEmpaque' AND Object_ID = Object_ID(N'dbo.tblEmpaques'))
            BEGIN
                EXEC sp_rename 'dbo.tblEmpaques.IdTamanoEmpaque', 'IdTamano', 'COLUMN';
            END
            """)

    operations = [
        migrations.RunPython(code=forwards_raw, reverse_code=backwards_raw),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='empaque',
                    name='tamano',
                    field=models.ForeignKey(blank=True, db_column='IdTamanoEmpaque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamano_empaque.tamanoempaque'),
                ),
            ],
            database_operations=[],
        ),
    ]
