# Generated by Django 5.0.14 on 2026-04-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empaques', '0011_empaque_nivel_molienda_state_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaque',
            name='notas',
            field=models.CharField(blank=True, db_column='Notas', max_length=500, null=True),
        ),
    ]
