# Generated by Django 5.0.14 on 2025-11-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblEmpleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblEmpleados',
                'managed': True,
            },
        ),
    ]
