# Generated by Django 5.0.14 on 2025-11-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('ordenes', '0008_orden_etiqueta_invima_orden_peso_orden_peso_bruto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblEmpleados',
            new_name='Empleado',
        ),
    ]
