# Generated by Django 5.0.14 on 2026-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_rename_tblempleados_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEmpleado',
            fields=[
                ('idEstadoEmpleado', models.AutoField(db_column='idEstadoEmpleado', primary_key=True, serialize=False)),
                ('Estado', models.CharField(db_column='Estado', max_length=50)),
            ],
            options={
                'db_table': 'tblEstadoEmpleados',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
    ]
