# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_tareas', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrilla',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('peso_cafe_bruto', models.FloatField(blank=True, db_column='PesoCafeBruto', null=True)),
                ('peso_cafe_verde', models.FloatField(blank=True, db_column='PesoCafeVerde', null=True)),
                ('rendimiento', models.FloatField(blank=True, db_column='Rendimiento', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('estado_tareas', models.ForeignKey(blank=True, db_column='IdEstadoTareas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_tareas.estadotarea')),
                ('orden', models.ForeignKey(blank=True, db_column='IdOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.orden')),
            ],
            options={
                'db_table': 'tblOrdenesTrilla',
            },
        ),
    ]
