# Generated by Django 5.0.14 on 2026-03-24 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_codigo_cliente'),
        ('ordenes_trilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrilla',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='IdCliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
