# Generated by Django 5.0.14 on 2026-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trilla', '0002_ordentrilla_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrilla',
            name='notas',
            field=models.CharField(blank=True, db_column='Notas', max_length=500, null=True),
        ),
    ]
