# Generated by Django 5.0.14 on 2026-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_seleccion_tostado', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenselecciontostado',
            name='notas',
            field=models.CharField(blank=True, db_column='notas', max_length=500, null=True),
        ),
    ]
