# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenSeleccionVerde',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('zaranda', models.BooleanField(blank=True, db_column='Zaranda', null=True)),
                ('grupo1', models.CharField(blank=True, db_column='Grupo1', max_length=10, null=True)),
                ('peso_grupo1', models.FloatField(blank=True, db_column='PesoGrupo1', null=True)),
                ('grupo2', models.CharField(blank=True, db_column='Grupo2', max_length=10, null=True)),
                ('peso_grupo2', models.FloatField(blank=True, db_column='PesoGrupo2', null=True)),
                ('grupo3', models.CharField(blank=True, db_column='Grupo3', max_length=10, null=True)),
                ('peso_grupo3', models.FloatField(blank=True, db_column='PesoGrupo3', null=True)),
                ('grupo4', models.CharField(blank=True, db_column='Grupo4', max_length=10, null=True)),
                ('peso_grupo4', models.FloatField(blank=True, db_column='PesoGrupo4', null=True)),
                ('grupo5', models.CharField(blank=True, db_column='Grupo5', max_length=10, null=True)),
                ('peso_grupo5', models.FloatField(blank=True, db_column='PesoGrupo5', null=True)),
                ('peso_grupo_ripio', models.FloatField(blank=True, db_column='PesoGrupoRipio', null=True)),
                ('catadora', models.BooleanField(blank=True, db_column='Catadora', null=True)),
                ('catacion_ripio', models.BooleanField(blank=True, db_column='CatacionRipio', null=True)),
                ('peso_cat_ripio', models.FloatField(blank=True, db_column='PesoCatRipio', null=True)),
                ('catacion_balsos', models.BooleanField(blank=True, db_column='CatacionBalsos', null=True)),
                ('peso_cat_balsos', models.FloatField(blank=True, db_column='PesoCatBalsos', null=True)),
                ('catacion_grupo1', models.BooleanField(blank=True, db_column='CatacionGrupo1', null=True)),
                ('peso_cat_grupo1', models.FloatField(blank=True, db_column='PesoCatGrupo1', null=True)),
                ('catacion_grupo2', models.BooleanField(blank=True, db_column='CatacionGrupo2', null=True)),
                ('peso_cat_grupo2', models.FloatField(blank=True, db_column='PesoCatGrupo2', null=True)),
                ('peso_aceptado', models.FloatField(blank=True, db_column='PesoAceptado', null=True)),
                ('medir_humedad', models.BooleanField(blank=True, db_column='MedirHumedad', null=True)),
                ('humedad', models.FloatField(blank=True, db_column='Humedad', null=True)),
                ('medir_densidad', models.BooleanField(blank=True, db_column='MedirDensidad', null=True)),
                ('densidad', models.FloatField(blank=True, db_column='Densidad', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('estado_tareas', models.ForeignKey(blank=True, db_column='IdEstadoTareas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_tareas.estadotarea')),
            ],
            options={
                'db_table': 'TblOrdenesSeleccionVerde',
            },
        ),
    ]
