# Generated by Django 5.0.14 on 2026-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_seleccion_verde', '0004_add_orden_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenseleccionverde',
            name='notas',
            field=models.CharField(blank=True, db_column='Notas', max_length=500, null=True),
        ),
    ]
