# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_inven_cafe', '0001_initial'),
        ('estado_tareas', '0001_initial'),
        ('nivel_molienda', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molienda',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('peso_moler', models.FloatField(blank=True, db_column='PesoMoler', null=True)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=40, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('estado_inven_cafe', models.ForeignKey(blank=True, db_column='IdInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_inven_cafe.estadoinvencafe')),
                ('estado_tarea', models.ForeignKey(blank=True, db_column='IdEstadoTarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_tareas.estadotarea')),
                ('nivel_molienda', models.ForeignKey(blank=True, db_column='IdNivelMolienda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nivel_molienda.nivelmolienda')),
                ('orden', models.ForeignKey(blank=True, db_column='IdOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.orden')),
            ],
            options={
                'db_table': 'tblMolienda',
            },
        ),
    ]
