# Generated by Django 5.0.7 on 2025-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_inven_cafe', '0001_initial'),
        ('estado_tareas', '0001_initial'),
        ('molienda', '0001_initial'),
        ('nivel_molienda', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='molienda',
            index=models.Index(fields=['fecha'], name='idx_molienda_fecha'),
        ),
    ]
