# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados_clientes', '0001_initial'),
        ('tipo_clientes', '0001_initial'),
        ('tipo_identificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=25, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=35, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=30, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('id_estado_cliente', models.ForeignKey(blank=True, db_column='IdEstadoCliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estados_clientes.estadocliente')),
                ('id_tipo_cliente', models.ForeignKey(blank=True, db_column='IdtipoCliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_clientes.tipocliente')),
                ('id_tipo_identificacion', models.ForeignKey(blank=True, db_column='IdTipoIdentificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_identificacion.tipoidentificacion')),
            ],
            options={
                'db_table': 'tblClientes',
            },
        ),
    ]
