# Generated by Django 5.0.7 on 2025-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('estados_clientes', '0001_initial'),
        ('tipo_clientes', '0001_initial'),
        ('tipo_identificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo'], name='idx_cliente_codigo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='idx_cliente_nombre'),
        ),
    ]
