# Generated by Django 5.0.14 on 2025-10-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_idx_cliente_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.CharField(blank=True, db_column='RepresentanteLegal', max_length=50, null=True),
        ),
    ]
