# Generated by Django 5.2.7 on 2025-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_codigo_cliente_autogenerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', null=True),
        ),
    ]
