# Generated by Django 5.2.7 on 2025-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_codigo_cliente_alter_cliente_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_ingreso',
        ),
            # Se elimina la operación AddField para evitar el error de columna duplicada
    ]
