# Generated by Django 5.0.14 on 2025-11-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_fecha_ingreso_cliente_codigo_cliente'),
    ]

    operations = [
        # Migración eliminada por duplicidad de columna CodigoCliente.
    ]
