# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empaques', '0001_initial'),
        ('estado_cafe', '0001_initial'),
        ('origen_cafe', '0001_initial'),
        ('proceso_inven_cafe', '0001_initial'),
        ('variendad_inven_cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioCafe',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('sacos', models.IntegerField(blank=True, db_column='Sacos', null=True)),
                ('cantidad_bolsas_emp', models.IntegerField(blank=True, db_column='CantidadBolsasEmp', null=True)),
                ('cantidad_paquetes', models.IntegerField(blank=True, db_column='CantidadPaquetes', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='IdClientes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('empaque', models.ForeignKey(blank=True, db_column='IdEmpaque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empaques.empaque')),
                ('estado_cafe', models.ForeignKey(blank=True, db_column='IdEstadoCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_cafe.estadocafe')),
                ('origen', models.ForeignKey(blank=True, db_column='IdOrigen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='origen_cafe.origencafe')),
                ('proceso_inven_cafe', models.ForeignKey(blank=True, db_column='IdProcesoInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proceso_inven_cafe.procesoinvencafe')),
                ('variendad_inven_cafe', models.ForeignKey(blank=True, db_column='IdVariendadInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='variendad_inven_cafe.variendadinvencafe')),
            ],
            options={
                'db_table': 'tblInventarioCafe',
            },
        ),
    ]
