# Generated by Django 5.0.7 on 2025-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_idx_cliente_codigo_and_more'),
        ('empaques', '0001_initial'),
        ('estado_cafe', '0001_initial'),
        ('inventario_cafe', '0001_initial'),
        ('origen_cafe', '0001_initial'),
        ('proceso_inven_cafe', '0001_initial'),
        ('variendad_inven_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventariocafe',
            index=models.Index(fields=['codigo'], name='idx_inv_codigo'),
        ),
        migrations.AddIndex(
            model_name='inventariocafe',
            index=models.Index(fields=['cliente'], name='idx_inv_cliente'),
        ),
        migrations.AddIndex(
            model_name='inventariocafe',
            index=models.Index(fields=['estado_cafe'], name='idx_inv_estado_cafe'),
        ),
    ]
