# Generated by Django 5.0.7 on 2025-09-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_empaque', '0002_alter_cafeempaque_id'),
        ('inventario_cafe', '0004_fix_idcafeempaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocafe',
            name='empaquecafe',
            field=models.ForeignKey(blank=True, db_column='IdEmpaqueCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_empaque.cafeempaque'),
        ),
    ]
