# Generated by Django 5.0.7 on 2025-09-15 01:25

# No-op migration to avoid accidental alteration conflicts
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('inventario_cafe', '0005_alter_inventariocafe_empaquecafe'),
    ]

    operations = []
