# Generated by Django 5.0.14 on 2025-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cafe', '0006_alter_inventariocafe_empaquecafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariocafe',
            name='descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True),
        ),
    ]
