# Generated by Django 5.0.14 on 2026-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cafe', '0007_inventariocafe_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocafe',
            name='codigo',
            field=models.CharField(blank=True, db_column='Codigo', max_length=26, null=True),
        ),
    ]