# Generated by Django 5.0.7 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelTueste',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nivel_tueste', models.CharField(blank=True, db_column='NivelTueste', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblNivelTueste',
            },
        ),
    ]
