# Generated by Django 5.0.7 on 2025-09-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('estado_inven_cafe', '0001_initial'),
        ('estado_ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(blank=True, db_column='FechaIngreso', null=True)),
                ('fecha_orden', models.DateTimeField(blank=True, db_column='FechaOrden', null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_column='FechaEntrega', null=True)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=30, null=True)),
                ('trilla', models.BooleanField(blank=True, db_column='Trilla', null=True)),
                ('selec_cafe_verde', models.BooleanField(blank=True, db_column='SelecCafeVerde', null=True)),
                ('tueste_flag', models.BooleanField(blank=True, db_column='Tueste', null=True)),
                ('selec_cafe_tostado', models.BooleanField(blank=True, db_column='SelecCafeTostado', null=True)),
                ('molienda_flag', models.BooleanField(blank=True, db_column='Molienda', null=True)),
                ('empaque_flag', models.BooleanField(blank=True, db_column='Empaque', null=True)),
                ('conf_trilla', models.BooleanField(blank=True, db_column='ConfTrilla', null=True)),
                ('conf_sel_verde', models.BooleanField(blank=True, db_column='ConfSelVerde', null=True)),
                ('conf_tueste', models.BooleanField(blank=True, db_column='ConfTueste', null=True)),
                ('conf_sel_tostado', models.BooleanField(blank=True, db_column='ConfSelTostado', null=True)),
                ('conf_molienda', models.BooleanField(blank=True, db_column='ConfMolienda', null=True)),
                ('conf_empaque', models.BooleanField(blank=True, db_column='ConfEmpaque', null=True)),
                ('prioridad', models.IntegerField(blank=True, db_column='Prioridad', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='IdClientes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('estado_inven_cafe', models.ForeignKey(blank=True, db_column='IdInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_inven_cafe.estadoinvencafe')),
                ('estado_orden', models.ForeignKey(blank=True, db_column='IdEstadoOrden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_ordenes.estadoorden')),
            ],
            options={
                'db_table': 'tblOrdenes',
            },
        ),
    ]
