# Generated by Django 5.0.7 on 2025-09-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_idx_cliente_codigo_and_more'),
        ('estado_inven_cafe', '0001_initial'),
        ('estado_ordenes', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_orden'], name='idx_orden_fecha'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['cliente'], name='idx_orden_cliente'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado_orden'], name='idx_orden_estado'),
        ),
    ]
