# Generated by Django 5.0.14 on 2025-09-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_cafe', '0001_initial'),
        ('ordenes', '0002_orden_idx_orden_fecha_orden_idx_orden_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado_inven_cafe',
            field=models.ForeignKey(blank=True, db_column='IdInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estado_cafe.estadocafe'),
        ),
    ]
