# Generated by Django 5.0.14 on 2025-11-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_fix_fk_orden_estado_cafe'),
    ]

    operations = [
        # Se elimina AddField porque la columna ya existe en la base de datos
    ]
