# Generated by Django 5.0.14 on 2025-11-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_orden_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='orden',
            field=models.CharField(blank=True, db_column='Orden', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
    ]
