# Generated by Django 5.0.14 on 2025-11-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_codigo_cliente'),
        ('estado_cafe', '0001_initial'),
        ('estado_ordenes', '0001_initial'),
        ('ordenes', '0006_orden_orden_alter_orden_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orden',
            name='idx_orden_fecha',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_orden',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_inicio_orden',
            field=models.DateTimeField(blank=True, db_column='FechaInicioOrden', null=True),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_inicio_orden'], name='idx_orden_fecha'),
        ),
    ]
