# Generated by Django 5.0.14 on 2025-11-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_remove_orden_idx_orden_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='etiqueta_invima',
            field=models.BooleanField(db_column='EtiquetaInvima', default=False, help_text='Indica si requiere etiqueta Invima en el empaque'),
        ),
        migrations.AddField(
            model_name='orden',
            name='peso',
            field=models.FloatField(blank=True, db_column='Peso', help_text='Peso neto total en kilogramos', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='peso_bruto',
            field=models.FloatField(blank=True, db_column='PesoBruto', help_text='Peso bruto total en kilogramos', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='sacos_entero',
            field=models.IntegerField(blank=True, db_column='SacosEntero', help_text='Número de sacos enteros procesados', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='trabajo_empaque',
            field=models.BooleanField(db_column='TrabajoEmpaque', default=False, help_text='Indica si el proceso incluye empaque manual'),
        ),
    ]
