# Generated by Django 5.0.14 on 2025-11-10 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_rename_tblempleados_empleado'),
        ('ordenes', '0008_orden_etiqueta_invima_orden_peso_orden_peso_bruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='IdEmpleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
