# Generated by Django 5.0.14 on 2025-11-15 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cafe', '0007_inventariocafe_descripcion'),
        ('ordenes', '0009_orden_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_inventario_cafe',
            field=models.ForeignKey(blank=True, db_column='IdInventarioCafe', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cafe.inventariocafe'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_inicio_orden',
            field=models.DateTimeField(blank=True, db_column='FechaIncioOrden', null=True),
        ),
    ]
