# Generated by Django 5.0.14 on 2026-03-19 03:17

import django.db.models.deletion
from django.db import migrations, models


def _sync_idinvencafe_fk_sqlserver(apps, schema_editor):
    if schema_editor.connection.vendor != 'microsoft':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_tblOrdenes_tblEstadoCafe')
            BEGIN
                ALTER TABLE [dbo].[tblOrdenes] DROP CONSTRAINT [FK_tblOrdenes_tblEstadoCafe];
            END;

            IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_tblOrdenes_tblEstadoInvenCafe')
            BEGIN
                ALTER TABLE [dbo].[tblOrdenes] DROP CONSTRAINT [FK_tblOrdenes_tblEstadoInvenCafe];
            END;

            IF EXISTS (
                SELECT 1
                FROM sys.columns
                WHERE object_id = OBJECT_ID(N'[dbo].[tblOrdenes]')
                  AND name = N'IdInvenCafe'
            )
            AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_tblOrdenes_tblInventarioCafe')
            BEGIN
                ALTER TABLE [dbo].[tblOrdenes] WITH CHECK ADD CONSTRAINT [FK_tblOrdenes_tblInventarioCafe]
                FOREIGN KEY([IdInvenCafe]) REFERENCES [dbo].[tblInventarioCafe] ([Id]);
                ALTER TABLE [dbo].[tblOrdenes] CHECK CONSTRAINT [FK_tblOrdenes_tblInventarioCafe];
            END;
            """
        )


def _sync_idinvencafe_fk_sqlserver_reverse(apps, schema_editor):
    if schema_editor.connection.vendor != 'microsoft':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_tblOrdenes_tblInventarioCafe')
            BEGIN
                ALTER TABLE [dbo].[tblOrdenes] DROP CONSTRAINT [FK_tblOrdenes_tblInventarioCafe];
            END;

            IF EXISTS (
                SELECT 1
                FROM sys.columns
                WHERE object_id = OBJECT_ID(N'[dbo].[tblOrdenes]')
                  AND name = N'IdInvenCafe'
            )
            AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_tblOrdenes_tblEstadoCafe')
            BEGIN
                ALTER TABLE [dbo].[tblOrdenes] WITH CHECK ADD CONSTRAINT [FK_tblOrdenes_tblEstadoCafe]
                FOREIGN KEY([IdInvenCafe]) REFERENCES [dbo].[tblEstadoCafe] ([Id]);
                ALTER TABLE [dbo].[tblOrdenes] CHECK CONSTRAINT [FK_tblOrdenes_tblEstadoCafe];
            END;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cafe', '0007_inventariocafe_descripcion'),
        ('ordenes', '0011_add_unique_orden'),
    ]

    operations = [
        migrations.RunPython(_sync_idinvencafe_fk_sqlserver, _sync_idinvencafe_fk_sqlserver_reverse),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='orden',
                    name='estado_inven_cafe',
                ),
                migrations.RemoveField(
                    model_name='orden',
                    name='id_inventario_cafe',
                ),
                migrations.AddField(
                    model_name='orden',
                    name='id_inven_cafe',
                    field=models.ForeignKey(blank=True, db_column='IdInvenCafe', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_cafe.inventariocafe'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='notas',
            field=models.CharField(blank=True, db_column='Notas', max_length=500, null=True),
        ),
    ]
