# Generated by Django 5.0.14 on 2026-04-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_remove_orden_estado_inven_cafe_and_more'),
        ('proceso_inven_cafe', '0001_initial'),
        ('variedad_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='proceso_inventario_cafe',
            field=models.ForeignKey(blank=True, db_column='IdProcesoInvenCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proceso_inven_cafe.procesoinvencafe'),
        ),
        migrations.AddField(
            model_name='orden',
            name='variedad_cafe',
            field=models.ForeignKey(blank=True, db_column='IdVariedadCafe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='variedad_cafe.variedadcafe'),
        ),
    ]
