# Generated by Django 5.0.7 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(blank=True, db_column='TipoCliente', max_length=35, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'tblTipoClientes',
            },
        ),
    ]
