# Generated by Django 5.0.7 on 2025-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCafe',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('estado_cafe', models.CharField(blank=True, db_column='EstadoCafe', max_length=35, null=True)),
            ],
            options={
                'db_table': 'tblEstadoCafe',
            },
        ),
    ]
