# Generated by Django 5.0.7 on 2025-09-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_empaque', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cafeempaque',
                    name='id',
                    field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
    ]
